# Generated by Django 5.0 on 2024-04-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prince',
        ),
    ]
