# Generated by Django 5.0 on 2024-04-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_order_prince'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
