# Generated by Django 5.0 on 2024-04-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_customer_infoaddress_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
