# Generated by Django 5.0 on 2024-04-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_customer_id_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoaddress',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='infoaddress',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
