# Generated by Django 5.0 on 2024-04-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_customer_id_infoaddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prince',
            new_name='price',
        ),
    ]
